version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  builder: dirhtml
  configuration: conf.py
  fail_on_warning: true

python:
  install:
    - requirements: requirements.txt
